# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23e7db42f08ad84a55d69a01386258c3045a2becb63f287bf9179e3b633eea14e791ee142198fda90390813ecf5bbd0a50793717449f92e7f51da5610330ddc1

test:
  secret_key_base: 5a7bcccaf4143253bfed39cf8bb478fc8b80e25120b8fcb09e6092c7b9f6d7a9ddd5eab10ceb5326af7bd32b917d7324312eaeb761695dc83e7fed4dc3ed0d0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
